### ISSUE TITLE
@example should perform escaping

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [jsdoc2md/jsdoc-to-markdown#12]
``` javascript
/** Perform foo
 * @example foo('<a href="#baz">hi!</a>');
 */
function foo(bar)
{
    return '<strong>' + bar + '</strong>';
};
```

`jsdoc test.js` gives me:

``` html
<pre class="prettyprint"><code>foo('&lt;a href="#baz">hi!&lt;/a>');</code></pre>
```

`jsdoc2md test.js` gives me:

``` markdown
<a name="foo"></a>
#foo()
Perform foo

**Example**
foo('<a href="#baz">hi!</a>');
```

That anchor is interpreted by markdown as html, this should probably be escaped or wrapped within a code block.

**Comment by 75lb** [comment]
here are the domv docs generated using the latest jsdoc2md code, how does it look?: https://github.com/75lb/domv/blob/master/api.md

1. implemented.. take a look at `domv/lib/HtmlDocument`.. if you click an inherited member in the class member index it takes you to the docs in the parent class (Component).. this reduces duplication in the docs (before, docs for inherited Component members were duplicated inside the docs for HtmlDocument).. 
2. this was caused by `<p>` tags in the domv jsdoc documentation that did not have a closing `</p>`.. 
3. done
4. done

**Comment by Joris-van-der-Wel** [comment]
awesome that looks much better! I do not see any other issues, thanks

I committed the missing `</p>`

**Comment by 75lb** [comment]
good, glad you like it.. i will package up a pre-release of jsdoc2md for you to experiment with.. will get back to you later..
