### ISSUE TITLE
Anchors and Gitbook

### ISSUE THREAD

**Issue by zandaqo** [jsdoc2md/jsdoc-to-markdown#125]
Hi,

I'm using jsdoc-to-markdown to generate API docs in a Gitbook. It all works quite nicely except for anchors. Gitbook uses the `id` attribute for anchors instead of the `name`. However, just changing partials to use a different attribute doesn't cut it because `id` attribute cannot use special symbols that jsdoc-to-markdown creates for its anchor names, e.g. `+` and `.` used for class instance and static methods. As a 
 temporary workaround I'm using a small helper that replaces those special symbols with underscores:
```
exports.escapedAnchor = function (anchor) {
  if (typeof anchor !== 'string') return null;
  return anchor.replace('+', '__').replace('.', '_');
};
```
This does the trick, but I was wondering if this can be somehow addressed in the library. From what I can tell, changing those symbols [here](https://github.com/jsdoc2md/dmd/blob/master/helpers/ddata.js#L573) should suffice. However, If supporting Gitbook's markdown isn't a priority, I'll try to create a dmd plugin for it.

**Comment by 75lb** [comment]
this issue [was raised recently](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/122) by @KevinAst.. Anchors have been an issue for a while as different sites (github, npm etc.) have different rules regarding them, so finding a solution to suit all targets has been awkward..

It's good your helper works but It's probably time I had a more detailed look. Meanwhile, @KevinAst may have some tips or insight..

**Comment by zandaqo** [comment]
Yes, I have seen that issue, but it was about the attribute's name rather than the incompatibility in the anchor naming, and the issue was closed, so I decided to open a new one.

To use anchors with `id` we have to observe the [limitations](https://www.w3.org/TR/html5/dom.html#the-id-attribute) that HTML puts on this attribute; there is no going around that. The question is what should be used for what. Personally, I'd reserve single underscore `_` for instance methods and properties instead of the current `+` (since there are more of them usually), maybe double underscore `__` for static methods, and special words like the current `_new` for the rest.

**Comment by KevinAst** [comment]
Hello @zandaqo,

Yes (as you know from [Issue122](https://github.com/jsdoc2md/jsdoc-to-markdown/issues/122)) I too am using partials to use anchor ids instead of name.

I just recently came across the id special character issue, so your post is a timely one.

While I understand what your temporary work around is doing, I **don't understand** 
  1. where it is injected and 
  2. how it is invoked.

**Can you shed a bit more light on this?** *(your assistance is greatly appreciated)*

In summary, there are two issues:

1. anchor employing id

   While this can be handled with partials, I believe it could be natively handled by jsdoc2md *(accommodating more environments without the need to override partials)*.

   I think that jsdoc2md could encode **both** the `name` and `id` attributes without penalty.  I have successfully done this in other contexts ... admittedly (however), not with the user base of jsdoc2md.

2. anchor id special character issue

   While the technique of replacing incompatible characters works, this has a bit of a code smell to me.

   From an html perspective, there is nothing inherently wrong with using the `'+'` and `'.'` characters within the anchor id.

   The **root issue** (in my mind) is the fact that Gitbook cannot handle these characters within it's JavaScript algorithm.  With that said, I'm not sure how responsive Gitbook would be in addressing this problem.

   **Thoughts?**

**Comment by zandaqo** [comment]
Hello, @KevinAst,

jsdoc2md gets its anchors from a helper called [`anchorName`](https://github.com/jsdoc2md/dmd/blob/master/helpers/ddata.js#L554) and uses it in templates as `{{{anchorName}}}`. Since jsdoc2md allows adding custom helpers, we can create a helper to modify the value returned by this `anchorName`. For example, we can place the code I wrote above in `helpers.js` and run jsdoc2md with `--helper helpers.js` command-line argument. Now we have to replace every use of `anchorName` helper in templates with our `escapedAnchor`. Since `anchorName` is also a helper, we have subexpression to use the output of one helper as the input of another, e.g.: `{{{escapedAnchor (anchorName)}}}`. So far I had to change the following partials: `header.hbs`, `sig-link.hbs`, `sig-link-html.hbs`, `sig-link-parent.hbs`. This makes it work in most cases, however there is still a problem with partials like `mixes.hbs` that uses `link` helper which uses jsdoc2md's `anchorName` internally and cannot be fixed in partials or by adding helpers.

`id` as per [standard](https://www.w3.org/TR/html5/dom.html#the-id-attribute) cannot contain special characters, hence, Gitbook has a good excuse not to handle such cases. The question is whether jsdoc2md is willing to support `id` along with `name` and impose the same limitations to both. Jsdoc2md is already [doing](https://github.com/jsdoc2md/dmd/blob/master/helpers/ddata.js#L569) name sanitation by replacing special characters like `~` and `#` in the names given by (I presume) jsdoc's AST. So it actually boils down to just finding a better replacement that conforms to id's restrictions.

**Comment by KevinAst** [comment]
Thanks @zandaqo for the detailed explanation of your workaround.

It's too bad there is not a technique to monkey-patch an exported module.  If this were available, you could centrally apply your patch:
- without the need to override all template usages of anchorName,
- and would also solve the issue with the internal usage of anchorName (by mixes.hbs).

**In regard to the [W3 standard for ids](https://www.w3.org/TR/html5/dom.html#the-id-attribute)**, I looked at this spec, but only see restrictions in using [space characters](https://www.w3.org/TR/html5/infrastructure.html#space-character).  **What am I missing?**

Thanks again!

**Comment by zandaqo** [comment]
@KevinAst You are actually right, I was getting my info on id from [HTML 4](https://www.w3.org/TR/html4/types.html#type-id) and didn't notice the changes in HTML5. If memory serves, in days of old, DOM used ids as object property names somewhere, and since then JS devs try to avoid special characters in ids, well, at least I do. Thanks for correcting!

I guess we do have a reason to bother Gitbook with this issue then.

**Comment by KevinAst** [comment]
@zandaqo ...  I successfully applied your work-around for the special characters fix.  This was much appreciated, as jsdoc2md has not yet documented the --helper feature.

With this work-around, the id's have been patched (ex: the dot `'.'` has been replaced with underbar `'_'`).  However the {@link xyz} tags are still not working, as they still reference the dot.  Is this the result of the the internal usage of anchorName (from mixes.hbs) that you mentioned?

As it turns out, this is not a big deal for me, because I am using a GitBook templating technique to do all my linking ... replacing all usage of the {@link} tag.  This allows me to seamlessly link between the Dev Guide and my API (and vice versa).

**SideBar**: Don't know what your experience was like in fully integrating Gitbook/JSDoc, but you may be interested in this article detailing my process: [Integrating GitBook with JSDoc to Document Your Open Source Project](https://medium.com/@kevinast/integrate-gitbook-jsdoc-974be8df6fb3).  One of it's topics is the linking technique that I mentioned (above).

Thanks again!

**Comment by zandaqo** [comment]
@KevinAst Yes, those links along with mixes and types are generated through `link` helper that uses `anchorName` internally. I cannot think of an easy fix for that short of rewriting the `link` helper itself. For now the situation is tolerable in my [case](https://scriptare.gitbooks.io/compago/API.html), but for complete support we have to either fix Gitbook's handling of the special characters or remove them from `anchorName` helper here, and preferably both in case some other markdown implementations also fail to account for special characters.

That's a nice tutorial you have written there. I have not advanced that far with Gitbook, so your article was very helpful. Thank you!

**Comment by truetamtam** [comment]
Thanks @zandaqo 
Wrote helper.
And, for my namespaced events, like "event.some.namespace", worked like this:
```javascript
exports.escapedAnchor = function (anchor) {
  if (typeof anchor !== 'string') return null;
  return anchor.replace('/\./g', '_');
};
```
