### ISSUE TITLE
support for `.mjs` files?

### ISSUE THREAD

**Issue by noahehall** [jsdoc2md/jsdoc-to-markdown#249]
currently returns `JSDOC_ERROR: There are no input files to process`

example here: https://github.com/noahehall/nodeproto/

**Comment by 75lb** [comment]
Hi, i created a wiki page to answer this.. let me know if you have any other issues.
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Documenting-.mjs,-.jsx-or-files-with-any-other-extension

**Comment by FagnerMartinsBrack** [comment]
> Hi, i created a wiki page to answer this.. let me know if you have any other issues.
https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/Documenting-.mjs,-.jsx-or-files-with-any-other-extension

The command doesn't work in "jsdoc-to-markdown": "1.3.1" using the guide from the Wiki:

```
➜  b2b git:(main) ✗ ./node_modules/.bin/jsdoc2md -c jsdoc.conf -f run.mjs
Error: There are no input files to process.
(run jsdoc2md with --verbose for a stack trace)

jsdoc-to-markdown

  Markdown API Documentation generator.

Synopsis

  $ jsdoc2md [options] --src file ...
  $ jsdoc2md --help
  $ jsdoc2md --config
  $ jsdoc2md --stats file ...
  $ jsdoc2md --json file ...

jsdoc2md

...
```

This command works:

```
./node_modules/.bin/jsdoc2md -c jsdoc.conf -f run.js
```

**Comment by 75lb** [comment]
is there any particular reason you're using jsdoc2md v1.3.1? It's over 9 years old..

**Comment by FagnerMartinsBrack** [comment]
> is there any particular reason you're using jsdoc2md v1.3.1? It's over 9 years old..

@75lb It's been 3 months since I wrote that comment so I lost the context of why I was using v1.3.1. I can briefly guess that I was likely using the binary file from a sub-dependency that was up to date but hadn't upgraded [jsdoc-to-markdown](https://github.com/jsdoc2md/jsdoc-to-markdown) to newer versions. This is very common in the NPM ecosystem, significant changes to the API tend to impact more people than you might think because of sub-dependencies and LeakyAbstractions. We should never assume everyone will always run the latest version as many projects gets stuck in Minor upgrades forever.

It would be useful to have a wiki with commands that work in different versions so developers can run the correct one that applies to that version and also for developers to be aware that there were breaking changes over the lifetime of the project 😄 
I probably had to reverse-engineer the code at the time to determine which arguments to run, which took some time but is achievable.

I hope that answers your question somehow, but I might be wrong about the root cause since my comment was 3 months ago and I moved on from that project 👍
