### ISSUE TITLE
"no input files to process" Regardless of Input provided

### ISSUE THREAD

**Issue by AQuackenbos** [jsdoc2md/jsdoc-to-markdown#259]
`jsdoc2md` appears to be ignoring both the include pattern in my config file, as well as any paths I provide it.

`jsdoc -c jsdoc.config.json` generates all documents appropriately to the output file defined in the config.  `jsdoc2md --no-cache -c jsdoc.config.json .` meanwhile produces the error: `JSDOC_ERROR: There are no input files to process.`

I have tried sending it a variety of paths and patterns in the last parameter but the error persists.  Below is the config file being used.  

```json
{
  "source": {
    "includePattern": ".+\\.js$",
    "exclude": [
      "node_modules"
    ]
  },
  "sourceType": "module",
  "opts": {
    "recurse": true,
    "destination": "docs"
  }
}
```

**Comment by 75lb** [comment]
this is the simple config i use - works for me locally: 

```
{
  "source": {
    "includePattern": ".+\\.(js(doc|x)?|mjs)$"
  }
}
```

I'm using node v16, macOS, jsdoc2md v7 and the command `jsdoc2md -c jsdoc.conf -t README.hbs index.mjs > README.md`.

I think your issue is with this command: ` jsdoc2md --no-cache -c jsdoc.config.json .`.. I think you are passing a direction (`.`) - you must pass file names.. 

You need something more like this: ` jsdoc2md --no-cache -c jsdoc.config.json *.js`

**Comment by 75lb** [comment]
re-open if you still have an issue
