### ISSUE TITLE
Docs missing inside the IIFE 

### ISSUE THREAD

**Issue by tenbits** [jsdoc2md/jsdoc-to-markdown#29]
Hi Team, 

is it possible to generate the docs from inside the IIFE. Consider this example
```javascript
var Foo;
(function(){
    /**
     * @summary I am Foo
     */
    Foo = {
        /**
         * @summary Print 'foo' to logs
         */
        log: function () {
            console.log('foo')
        }
    };
}());
```
```bash
jsdoc2md src/foo.js > api.md
```

`jsdoc2md` generates an empty file. Only the commenting of the lines  2 and the last one (`iife` call) makes the docs to be created. Though `jsdoc-parse` works as expected for both of the variants. 

Thanks, Alex

**Comment by 75lb** [comment]
hi alex, thanks for the report.. yes, it's a known issue and i one i would like to address.. i will look into it tomorrow..

**Comment by tenbits** [comment]
Thanks, Lloyd. I'm not sure if this helps, but I noticed the DocRenderer ignores the nodes in a tree with `memberof:anonymous`.  And thank you for your work, nice project structure ..

**Comment by 75lb** [comment]
sorry for the delay in actioning this important issue! i lost my damn laptop a week ago - left it on the tube.. i'll get a new one in the next couple of days and get back on it..

**Comment by tenbits** [comment]
Oh, it is a pitty to lose things, espaccially all the e-gadgets. But I really hope you have all the backups. May be you also have to consider to change all your sensitive passwords.

**Comment by tenbits** [comment]
Hi Lloyd, any progress on the issue?

**Comment by 75lb** [comment]
not yet, i'm still progressing a couple of other things on the list.. but i'll take a preliminary look tonight, after work.. will get back to you.. 

how are you handling it in the meantime? with a workaround? or no docs at all?

**Comment by tenbits** [comment]
Thanks for looking into this issue. 

> No docs at all

:smile:  As usual, there are a lot of other things on my todos, and no time for finding a workaround.

**Comment by 75lb** [comment]
well, no docs is no use at all.. will get onto it.

**Comment by g-ortuno** [comment]
Any updates on this?

**Comment by 75lb** [comment]
hi, not yet but i plan to begin work on jsdoc2md v2 very soon - hopefully within a week or two.. this, and all issues will be addressed.

**Comment by 75lb** [comment]
just as a bit of background, lack of IIFE support is a long-running issue with jsdoc (see [here](https://github.com/jsdoc3/jsdoc/issues/456), [here](https://github.com/jsdoc3/jsdoc/issues/442)).. some workarounds are suggested in the comments, [this one](https://github.com/jsdoc3/jsdoc/issues/442#issuecomment-30307214) seems worth a try.. 

meanwhile i'll have a think how to represent these docs in jsdoc2md..

**Comment by 75lb** [comment]
The main issue with an IIFE is scope.. should doclets inside an IIFE be marked as global? Module scope? As a member of an object? Jsdoc has not addressed this issues in years, i think because it's very difficult to answer these questions with static analysis - so we are expected to provide clues using tags like `@public`, `@alias` etc. 

@g-ortuno I had a look at your project and sent a [PR](https://github.com/google/eddystone/pull/111) which some suggestions how to more accurately reflect the architecture of your codebase. 

@tenbits Could you point me at a project using IIFEs or send a more complete example? A private gist is fine - I'd like to see your use case. 

Long term, we probably need to establish a new scope.. currently, IIFEs do not make it into the rendered docs as they have no "place" - they do not fit into the general outline of the document (they are not part of a module, the global scope, a parent object etc.) The two solutions are

1. Use additional tags (`@alias` etc) to more verbosely give the doclets a "place" in the project architecture.
2. Just bunch IIFEs up at the footer of the output under the label "Immediately Executed" or similar.
