### ISSUE TITLE
Doc not generate and no error message

### ISSUE THREAD

**Issue by alanschiobairesdev** [jsdoc2md/jsdoc-to-markdown#296]
I have the following js file https://gist.github.com/alanschiobairesdev/478c33f834f74c0e559556708f2cb3be
jsdoc can succefully generate it, but jsdoc-to-mardown do no generate, and not erros is give only `✨  Done in 0.30s.`. but no file
![Screenshot 2024-01-18 at 14 03 17](https://github.com/jsdoc2md/jsdoc-to-markdown/assets/146004046/30e79f3b-73db-467c-a621-cdfc87cdde0a)

package json
```json
{
  "name": "jsdoc2mdteste",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "jsdoc": "^4.0.2",
    "jsdoc-to-markdown": "^8.0.0"
  }
}
```

no matter if `yarn run jsdoc2md example.js` or `yarn jsdoc2md example.js` none generate the md file.

**Comment by fergiemcdowall** [comment]
Same here- `jsdoc` works, but `jsdoc2md` simply exits silently.

**Comment by 75lb** [comment]
Add this to the top of the file: 

```
/**
 * @module my-module-file
 */
```

I know, it's because the documented class is a child (in the underlying data structure) of an undocumented module. Undocumented identifiers/modules are skipped, resulting in their children being skipped too. [See this](https://github.com/jsdoc2md/jsdoc-to-markdown/wiki/How-to-document-an-ES2015-module-(multiple-named-exports)).
