### ISSUE TITLE
Error: The partial main could not be found

### ISSUE THREAD

**Issue by lijuhong1981** [jsdoc2md/jsdoc-to-markdown#300]
I use the "jsdoc2md src/index.js" command, report error:
“Error: The partial main could not be found”
The jsdoc-to-markdown version is 8.0.2.

**Comment by lijuhong1981** [comment]
The version 8.0.1 can be used.
But if update to 8.0.2 version, use it report error: “Error: The partial main could not be found”.

**Comment by 75lb** [comment]
I can't reproduce this.. Could you uninstall then reinstall jsdoc2md and try again.. if it still fails, please post a reproduction case here which I can run to see it fail.. I will need to see the full command you use plus a JS file which fails.

**Comment by lijuhong1981** [comment]
Reinstall and try again still fails.
The version is 8.0.2.
I created a whole new project still fails.
[jsdoc2md.zip](https://github.com/user-attachments/files/16355978/jsdoc2md.zip)

**Comment by KhromovNikita** [comment]
I also get a similar error: Error: The partial main could not be found

**Comment by 75lb** [comment]
> Reinstall and try again still fails. The node version is 20.10.0. I created a whole new project still fails. [jsdoc2md.zip](https://github.com/user-attachments/files/16355978/jsdoc2md.zip)

I'm on macOS.. from this project I tried `npm run build-docs` in node 12, 15, 16, 18 and 22 and everything worked correctly.. which OS are you on?

**Comment by lijuhong1981** [comment]
windows 10

**Comment by 75lb** [comment]
Fixed in v8.0.3 - please reinstall and try again. 

Fast-glob on windows was the issue. I replaced node-glob with fast-glob recently as node-glob does not support old Node.js versions (jsdoc2md requires support back to v12).. I have rolled back to node-glob for now, while I look more closely at the fast-glob windows issue. Many thanks for the quick bug report! 

/cc https://github.com/jsdoc2md/jsdoc-api/pull/28
