### ISSUE TITLE
Class instance name - last letter is capital

### ISSUE THREAD

**Issue by scholtzm** [jsdoc2md/jsdoc-to-markdown#38]
For some reason the class instance names have last letter capitalized in my docs, e.g.

```
new API() <-- correct
apI.shutdown() <-- every API method is like this
```

[Here are the generated markdown docs.](https://github.com/scholtzm/vapor/blob/master/docs/API.md) Notice how the Utils class is capitalized correctly.

**Comment by 75lb** [comment]
i apologise for the delay! 

you can override the parent object name in child property docs using `@typicalname`.. i sent a PR to demonstrate this.. he's how the output looks: 
https://github.com/75lb/vapor/blob/master/docs/API.md

**Comment by scholtzm** [comment]
Alright, thanks. However, how come the Utils class doesn't need this and the API class does?

**Comment by 75lb** [comment]
hi! it's because dmd attempts to camelCase the parent object name for member docs.. but it's quite an opinionated arena and not everyone likes the auto-camel-case output.. for example, should 'JSONStream' camelCase to 'jsonStream', 'jSONStream' or 'jsoNStream'? The correct answer differs from case to case.. 

the solution - set your own `@typicalname`

**Comment by 75lb** [comment]
`@typicalname` is documented briefly at the top of [jsdoc-parse](https://github.com/jsdoc2md/jsdoc-parse)

**Comment by scholtzm** [comment]
That makes sense, thanks for the explanation.
