### ISSUE TITLE
Is there a way to parse markdown within tags? (similar to markdown plugin within jsdoc)

### ISSUE THREAD

**Issue by ambischof** [jsdoc2md/jsdoc-to-markdown#71]
http://usejsdoc.org/plugins-markdown.html
I'd kind of like to be able to use markdown within tags like param.

If it's not something that can happen, is there any way to have at least line breaks? They seem to all be stripped.

**Comment by 75lb** [comment]
Normally with markdown you end a line with two blank spaces to get a linebreak, is this not working for you?

**Comment by ambischof** [comment]
Nope, not within tags like @param.

**Comment by 75lb** [comment]
if you look at `0-src.js` in [this example](https://github.com/jsdoc2md/testbed/tree/master/build/jsdoc/global/param-markdown) you can see markdown in the param descriptions.. `3-dmd.md` is rendered using the default options and you can see the markdown is lost - this is by design as GFM tables do not support embedded markdown or new lines. 

so, use the `--no-gfm` option.. [example output](https://github.com/jsdoc2md/testbed/blob/master/build/jsdoc2md/dmd-options/no-gfm/param-list/3-dmd.md).

you can see [here](https://github.com/jsdoc2md/testbed/blob/master/build/jsdoc2md/dmd-options/param-list-format/3-dmd.md) that multiline also works with `--param-list-format list`.

**Comment by ambischof** [comment]
You're right, the `--no-gfm` does work; it also allows the markdown to be parsed.

Thanks! I never would have guessed that was the issue.

**Comment by 75lb** [comment]
yeah, it's not obvious which problems `no-gfm` solves.. will improve that in v2

**Comment by ambischof** [comment]
Bleh, now I have an issue. Just realized that the --no-gfm tag makes tables render wrong in the bitbucket version. Guess I gotta make an issue over at that repo.
